apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD AppProject
  - monitoring-project.yaml
  # Kubernetes Resources
  - grafana-secret.yaml
  - network-policy.yaml
  # ArgoCD Applications
  - prometheus-app.yaml
  - loki-app.yaml
  - promtail-app.yaml
