apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  template:
    spec:
      containers:
        - name: auth-service-container
          env:
            - name: INTERNAL_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: prod-app-secrets
                  key: INTERNAL_API_SECRET
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-app-secrets
                  key: JWT_PRIVATE_KEY
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-app-secrets
                  key: JWT_PUBLIC_KEY
