apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-base.yaml
  - istiod.yaml
  - istio-ingressgateway.yaml
  - kube-prometheus-stack.yaml
  - loki-stack.yaml
  - kiali.yaml
  - external-secrets-operator.yaml
